### ISSUE TITLE
[Bug] Updating subscription-item quantity doesn't trigger proration or webhooks

### ISSUE THREAD

**Issue by iwasrobbed** [lmsqueezy/lemonsqueezy.js#105]
I'm building a SaaS product that requires seats within a subscription.

While testing a simple [update of a subscription's quantity](https://docs.lemonsqueezy.com/guides/developer-guide/usage-based-billing#updating-quantity) after initial purchase (while using `invoice_immediately`), I noticed that a `subscription_updated` webhook is not triggered at all and neither is any sort of $ dollar amount on the subscription to show that they are being charged e.g. double for 2 seats rather than one.

For example, if they originally purchased a "Professional" plan for $29/mo and then added another seat it should now charge them 2*29 = $58/mo for that subscription.

I even tried not using the SDK and just doing fetch requests, which you can view with the console logs here: https://gist.github.com/iwasrobbed/2207f9ce37b57358c18d97eda067b438

### Expected API behavior
Especially while using `invoice_immediately`:

- Updating "quantity" of a `subscription_item` should send a webhook that the subscription changed
- Updating "quantity" of a `subscription_item` should change the dollar amount being charged to the customer, and that should be reflected in an email (to the customer / store owner) as well as in the Lemon Squeezy store

Am I misunderstanding [the docs](https://docs.lemonsqueezy.com/guides/developer-guide/usage-based-billing#updating-quantity)?

### Web app behavior

Oddly, the Lemon Squeezy web app uses a different endpoint which _**does**_ work as described above

```curl
fetch("https://app.lemonsqueezy.com/subscriptions/413536/edit", {
  "headers": { ... },
  "body": "{\"product_id\":286156,\"variant_id\":407132,\"quantity\":10,\"invoice_immediately\":false,\"disable_prorations\":false,\"billing_behaviour\":\"immediately-with-proration\"}",
  "method": "PATCH"
});
```

but trying to use the same `immediately-with-proration` via API gets rejected.

### Others who have experienced this
- https://laracasts.com/discuss/channels/general-discussion/how-to-automatically-bill-a-customer-when-changing-the-quantity-of-a-subscription-item-via-the-lemon-squeezy-api
- https://x.com/lovinjerry004/status/1763931894159212997
- https://x.com/rafal_makes/status/1792055587066232880

**Comment by iwasrobbed** [comment]
A fix for this specific issue has been pushed, per https://makelemonadewtf.slack.com/archives/C03RF706XL2/p1718626381295279

🐛 But seeing quite a few other bugs around revenue reporting, double-charging of sales tax, sending teammates my order emails, etc.

Not sure how best to report so many issues.

**Comment by brankoconjic** [comment]
Could you please send me a list of the issues to my email (branko[at]lemonsqueezy.com)? I will make sure to expedite them as soon as possible.

**Comment by iwasrobbed** [comment]
Just sent, thanks @brankoconjic !
