### ISSUE TITLE
Cannot pay in test mode

### ISSUE THREAD

**Issue by Sprheany** [lmsqueezy/lemonsqueezy.js#107]
An internal server error of 500 occurred with this request: `https://{store}.lemonsqueezy.com/checkout/authorize?cart=xxxx`
```
{
    "message": "An unexpected error occurred.",
    "request_id": "5c0b1599-58a5-4387-8545-5d8b3017eb11"
}
```

Checkout URL create(embed=false):
``` 
  const checkout = await createCheckout(LEMONSQUEEZY_STORE_ID, variantId, {
    checkoutOptions: {
      embed,
      media: false,
      logo: !embed,
    },
    checkoutData: {
      email: user.email || undefined,
      name: user.name || undefined,
      custom: {
        user_id: user.id,
      },
    },
    productOptions: {
      enabledVariants: [variantId],
    },
  });

  return checkout.data?.data.attributes.url;
```

**Comment by keyding** [comment]
I tested the checkout URL generated by the `createCheckout` function, and there are no issues.

Here is the test code:

```ts
const storeId = import.meta.env.LEMON_SQUEEZY_STORE_ID;
const variantId = 220535

const { data } = await createCheckout(storeId, variantId, {
  checkoutOptions: {
    embed: false,
    media: false,
    logo: true,
  },  
  checkoutData: {
    email: "tita0x00@gmail.com",
    name: "Lemon Squeezy Test",
    custom: {
      user_id: "1234567890",
    }
  },
  productOptions: {
    enabledVariants: [variantId],
  },
})

console.log(data?.data.attributes.url);
// https://store.amazonus.app/checkout/custom/f2db9494-c73a-4c39-9a33-3d77564aa5a1?signature=1d59c0567075f0338432bbdde4834150535f13e7f474ae20101777b409757b76
```

The link opens fine.

![Checkout](https://github.com/lmsqueezy/lemonsqueezy.js/assets/20431351/324bc3a9-4fea-4962-8a11-bc62b94fb6a3)

Test order success.

![order](https://github.com/lmsqueezy/lemonsqueezy.js/assets/20431351/786fe324-37be-4aa7-a524-8090d9dc2489)

Could you provide a more detailed usage process?

Hope this can help you.

**Comment by Sprheany** [comment]
@keyding 

Use your checkout url still failed: https://store.amazonus.app/checkout/custom/f2db9494-c73a-4c39-9a33-3d77564aa5a1?signature=1d59c0567075f0338432bbdde4834150535f13e7f474ae20101777b409757b76
![Jietu20240710-173743](https://github.com/lmsqueezy/lemonsqueezy.js/assets/7323477/08317836-b373-4bec-aa5b-2dccb26f2fd8)
![Jietu20240710-174017@2x](https://github.com/lmsqueezy/lemonsqueezy.js/assets/7323477/706034c6-cb97-47b2-967f-a2a7d8ce8161)

**Comment by keyding** [comment]
I tested the `Edge` browser and reproduced your issue. I suspect it might be a server-side problem.

**Comment by Sprheany** [comment]
I tested the Chrome and Safari, got the same error.
