### ISSUE TITLE
Webhook isn't being received, and a post request to the same link is being received

### ISSUE THREAD

**Issue by MehdiMamas** [lmsqueezy/lemonsqueezy.js#108]
<img width="685" alt="image" src="https://github.com/user-attachments/assets/16e580f3-dcd5-4881-b2e7-fa8dd43f55f8">

<img width="1018" alt="image" src="https://github.com/user-attachments/assets/569afc57-17c8-4da4-8adf-f0494d3021fa">

Hey,

I have an issue with the webhooks. I did many tests to get it to work but to no avail.

Could you please help me?

**Comment by MehdiMamas** [comment]
Also, I did check the past issues, no one seems to talk about this, and the slack link is not working therefore I couldn't join the community and ask about it.

Please guide me to fix this issue.

**Comment by keyding** [comment]
Hi, @MehdiMamas 

I tested with [webhook.site](https://webhook.site) and it is fine.

![2024-07-24 at 12 27 46](https://github.com/user-attachments/assets/09e00a28-bd16-4bac-81c7-8a9a923b1206)

I hope this helps.

**Comment by MehdiMamas** [comment]
I see, do you by any chance have an idea why this is happening although postman is able to access the same link?

**Comment by keyding** [comment]
I'm not quite sure exactly why, I'm guessing it could be the network or checking your webhook api's response and status code

**Comment by MehdiMamas** [comment]
I actually made the api so that it always returns 200 status to check and it still didn't work 😅😅.

**Comment by MehdiMamas** [comment]
I don't think this is related to any identity verification or something similar right?

Because I did debug the server and it appears that the POST request is never detected as if it was stopped before even accessing the POST request, I checked if CORS could be the reason, but it also didn't work.

The only thing that I am suspicious of is the fact that I am using nginx to forward port 3000 to 443. But as you can see https is working fine with no issues, so it's really confusing me. Please let me know if there are any other troubleshooting steps or at least the error received from the webhook, because I have been getting 400 status code, but according to the debugging it's more like a 404 status code.

Sorry for the disturbance.

**Comment by MehdiMamas** [comment]
Update: just removed nginx to test my suspicion. Nginx is not the issue, still not working.

**Comment by MehdiMamas** [comment]
Update: I tried a random url that doesn't exist, and I get the same response "400 no response". Still confused why is that even though clearly the POST request exists.

**Comment by MehdiMamas** [comment]
```
app.post("*", (req, res) => {
  res.status(200).send("ok");
});
```

I even used this, and it didn't work...

**Comment by MehdiMamas** [comment]
Could it be because of CrowdStrike? since I am using AWS? I mean I really doubt that Amazon will leave such big issue around for too long.

**Comment by MehdiMamas** [comment]
It turned out that the SSL is faulty, and my postman had SSL verification disabled.
