### ISSUE TITLE
Incorrect proration amount calculation while upgrading

### ISSUE THREAD

**Issue by SantoshKumarRavi** [lmsqueezy/lemonsqueezy.js#109]
### Description:
We are experiencing issues with proration calculation.

### Store Details:
Currency: INR

### Issues:

1. Proration Calculation:
   - We have set our store currency to INR and created multiple products in INR.
   - The initial subscription works correctly. However, if a user upgrades to a higher plan, the proration calculation is incorrect.
   - For example, if I sell products for 10 INR and 20 INR, when a user changes from the 10 INR product to the 20 INR product, they should pay the remaining 10 INR, which should be approximately 0.11 USD (10/83.71, current conversion rate). Instead, the system is calculating it as 830 INR (10 * 83).

### Steps to Reproduce:
1. Set store currency to INR.
2. Create products with prices in INR.
3. Subscribe to a product.
4. Attempt to upgrade to a higher plan.
5. Observe the proration calculation.
6. Attempt to change subscription from monthly to yearly.
7. Observe the proration calculation.

### Expected Behavior:
Proration calculation should be accurate based on the currency conversion rate.

### Actual Behavior:
Proration calculation is incorrect, multiplying the INR amount by the conversion rate instead of dividing.

### Screen shot:

![Screenshot (2323)](https://github.com/user-attachments/assets/d107b941-eaae-4b69-82d4-bcc06aa7f358)
As shown in the attached image, we subscribed to a product for 708 INR and then upgraded to a product priced at 1500 INR. However, the proration calculation resulted in an incorrect amount of 127,704.45 INR instead of the expected 1500 INR.

**Comment by brankoconjic** [comment]
Hey @SantoshKumarRavi,

I've let our team know about the issue, and we are looking into it further. I will close this issue since this is not the appropriate channel for Lemon Squeezy support.

If you have further questions you can [contact our support team](https://www.lemonsqueezy.com/help).
