### ISSUE TITLE
Request for PayPal Payment Test Credentials

### ISSUE THREAD

**Issue by SantoshKumarRavi** [lmsqueezy/lemonsqueezy.js#111]
### Description:
- We are requesting PayPal payment test credentials for our Lemon Squeezy account to thoroughly test the PayPal payment integration in our production store.

- We referred to the documentation at https://docs.lemonsqueezy.com/help/getting-started/test-mode, but we only found test credit card information. There were no details regarding PayPal test credentials.

- It also redirecting to production paypal instead of sandbox paypal

### Screenshots: 
![Screenshot (2325)](https://github.com/user-attachments/assets/6ebc8bc5-6d24-4d67-bd67-c161b0bf5de2)

**Comment by brankoconjic** [comment]
We don't have support for PayPal test payments at the moment. You can suggest that feature here: https://www.lemonsqueezy.com/suggest-feature
