### ISSUE TITLE
Crash when creating lemonsqueezy script in SvelteKit app

### ISSUE THREAD

**Issue by erikjalevik** [lmsqueezy/lemonsqueezy.js#112]
When used with SvelteKit, and initialised on mount, we often see "TypeError: window.createLemonSqueezy is not a function" and thereafter the whole app state is broken causing SvelteKit to crash internally.

A minimal reproducible test case is here:

https://github.com/erikjalevik/lemonsqueezy-sveltekit-crash

It's a plain SvelteKit boilerplate project with one route added that submits a form to a server-side handler.

Detailed instructions are in the README, but I'll duplicate them here as well:

This repo demonstrates a crash when submitting a form in SvelteKit that happens only when the lemon.js script is present. The lemon.js script is added to `src/app.html`, and `createLemonSqueezy()` is called when the component in `src/routes/+page.svelte` mounts, as instructed by the documentation.

To reproduce:

1. Clone repo.
1. `npm i`
1. `npm run build`
1. `npm run preview`
1. Open browser console.
1. Visit http://localhost:4173/

Directly on load, we see a "TypeError: window.createLemonSqueezy is not a function" error message. If we thereafter try to submit the form by clicking the button, SvelteKit crashes with "TypeError: Cannot read properties of undefined (reading '$set')".

If we remove the line `(window as any).createLemonSqueezy();` from `onMount`, everything works as expected.

The bug seems easier to reproduce in a production build (i.e. `npm run build`), but can also be reproduced in dev mode (`npm run dev`), by reloading the page until we see the error being logged.

**Comment by brankoconjic** [comment]
Hey @erikjalevik,

Because the script is loaded asynchronously (`defer`), it loads after the page has already loaded. As a result, when you call `window.createLemonSqueezy()` in `onMount`, the method may (and most likely) not be available at that point.

I haven't worked with Svelte, but here's something you can try:

1. In your page load script like this:

```svelte
<svelte:head>
    <script src="https://app.lemonsqueezy.com/js/lemon.js" on:load={loadLS} defer></script>
</svelte:head>
```

Use `on:load` instead of `onMount` to call `window.createLemonSqueezy();`


2. Declare `LemonSqueezy` object and `createLemonSqueezy()` method in your `app.d.ts` file to let TS be aware of it:

```ts
declare global {
  namespace App {
  }

  interface Window {
    createLemonSqueezy: () => void;
    LemonSqueezy: {
      /**
       * Initialises Lemon.js on your page.
       * @param options - An object with a single property, eventHandler, which is a function that will be called when Lemon.js emits an event.
       */
      Setup: (options: { eventHandler: (event: { event: string }) => void }) => void;
      /**
       * Refreshes `lemonsqueezy-button` listeners on the page.
       */
      Refresh: () => void;

      Url: {
        /**
         * Opens a given Lemon Squeezy URL, typically these are Checkout or Payment Details Update overlays.
         * @param url - The URL to open.
         */
        Open: (url: string) => void;

        /**
         * Closes the current opened Lemon Squeezy overlay checkout window.
         */
        Close: () => void;
      };
      Affiliate: {
        /**
         * Retrieve the affiliate tracking ID
         */
        GetID: () => string;

        /**
         * Append the affiliate tracking parameter to the given URL
         * @param url - The URL to append the affiliate tracking parameter to.
         */
        Build: (url: string) => string;
      };
    };
  }
}
```

**Comment by erikjalevik** [comment]
Thanks for the answer and for taking the time to provide a PR! That does indeed seem to fix it. I chose `onMount` since that's what the [docs here](https://docs.lemonsqueezy.com/help/lemonjs/what-is-lemonjs#default-behaviour-with-js-frameworks) suggested.  But if the `load` event of the script is the way to go, we'll use that from now on!

Still, a bit strange that failing to load LemonSqueezy would cause an entirely unrelated object inside SvelteKit to become undefined...
