### ISSUE TITLE
Dark mode doesn't work

### ISSUE THREAD

**Issue by viperxeyes** [lmsqueezy/lemonsqueezy.js#114]
I have Next JS 14 app , which uses tailwind and next-theme , I also havea  theme switcher in my header which switch the theme with no issues , but not matter what  , the checkout page doesn't resepect the theme , even if i pass the dark:true in the api call

```
"use server";

import currentUser from "@/hooks/currentUser";
import { configureLemonSqueezy } from "@/lib/lemonsqueezy-config";
import { createCheckout } from "@lemonsqueezy/lemonsqueezy.js";
import { redirect } from "next/navigation";

export async function getCheckoutURL(variantId = "471509", embed = false) {
  configureLemonSqueezy();

  const user = await currentUser();

  if (!user) {
    redirect("/auth/login");
  }

  // import { createCheckout } from '@lemonsqueezy/lemonsqueezy.js'
  const checkout = await createCheckout(
    process.env.LEMONSQUEEZY_STORE_ID,
    variantId,
    {
      checkoutOptions: {
        embed,
        media: true,
        logo: true,
        desc: false,
      },
      checkoutData: {
        email: user.email ?? undefined,
        name: user.name ?? undefined,
        billingAddress: {
          country: "EG",
          zip: "12658",
        },

        custom: {
          user_id: user.id,
        },
      },
      productOptions: {
        enabledVariants: [variantId],
        redirectUrl:
          process.env.NODE_ENV == "development"
            ? "http://localhost:3000/dashboard"
            : `${process.env.NEXT_PUBLIC_URL}/billing/`,
        receiptButtonText: "Go to Dashboard",
        receiptThankYouNote: "Thank you for signing up to Lemon Stand!",
      },
    }
  );

  return checkout.data?.data.attributes.url;
}
```

**Comment by keyding** [comment]
It doesn't look like the problem you describe is related to the following code.

**Comment by bluemods** [comment]
I have the same issue, `data.attributes.checkout_options.dark` flag in create checkout request doesn't work, at least on desktop.

Creating it like this:

```kotlin
    @JvmOverloads
    fun createBotCheckout(
        variant: BotVariant,
        darkMode: Boolean = false,
        expiresAfter: Duration? = null,
        customKeys: Map<String, String> = emptyMap(),
        options: Checkout.ProductOptions? = null
    ): Promise<Checkout> {
        return api.createCheckout(CreateCheckoutRequest(
            storeId = storeId,
            variantId = variant.getVariantId(this),
            preview = false,
            testMode = isTestMode,
            expiresAt = expiresAfter?.let { Date(System.currentTimeMillis()+expiresAfter.toMillis()) },
            productOptions = options,
            checkoutOptions = Checkout.CheckoutOptions(
                embed = true,
                media = true,
                logo = false,
                desc = true,
                discount = true,
                skipTrial = true,
                subscriptionPreview = true,
                dark = darkMode,
            ),
            checkoutData = Checkout.CheckoutData(
                custom = encryptExtras(customKeys),
                discountCode = null
            )
        ))
    }
```

**Comment by Skippou** [comment]
Same here, dark mode checkout doesn't work. At least not on test mode. I haven't tried production.

Tried both methods. Setting the checkout config,
```
checkoutOptions: {
    dark: true,
}
```
, and with the api parameters ?dark=true

**Comment by brankoconjic** [comment]
Hey all,

The `dark` option was deprecated in favor of [themes](https://docs.lemonsqueezy.com/help/online-store/customization).

The docs and the SDK will be updated on Monday to remove the option.

**Comment by bluemods** [comment]
Please consider restoring it or allowing custom themes to be chosen.

The use case for this (which I'm sure many other sites share) is that many sites nowadays have at least a light / dark mode toggle. It would be great to be able to use the checkouts API to dynamically create a checkout that somewhat matches the current theme of your site, which was my goal.

**Comment by gerritcloete** [comment]
The new colour options do not allow for a complete customised dark checkout. The main checkout div is styled with "rounded bg-white shadow-menu". Is this on purpose?

**Comment by Yiidiir** [comment]
> The new colour options do not allow for a complete customised dark checkout. The main checkout div is styled with "rounded bg-white shadow-menu". Is this on purpose?

exactly this @brankoconjic  @branko-stripe

**Comment by branko-stripe** [comment]
@Yiidiir yes, it's on purpose and cannot be customized.

**Comment by Yiidiir** [comment]
@branko-stripe are you saying we can't get this to work? 
https://x.com/lmsqueezy/status/1650583900136120320/photo/1

Is there a specific reason not to allow it? Dark mode is a standard and this breaks the UX..

Does this have to do with Stripe acquisition?
