### ISSUE TITLE
Clarification on Subscription Status Change During Upgrade Payment Failures

### ISSUE THREAD

**Issue by SantoshKumarRavi** [lmsqueezy/lemonsqueezy.js#119]
I am writing to seek clarification regarding the behavior of subscription status changes during upgrade payment failures. According to the LS documentation, renewal payment failures change the subscription status to past_due. However, we have encountered a scenario that requires further understanding.

In our current setup, when a user attempts to upgrade their subscription and the payment fails, the subscription status changes to past_due. The user then receives emails prompting them to confirm the update, which works as expected if they complete the update.

Our concern is regarding the scenario where the user does not proceed with the upgrade from the email or any link provided by LS. Will the subscription eventually expire after some retries and dunning management, even if the user has already paid for the current billing period with a lesser quantity?

We would appreciate your guidance on this matter to ensure our subscription management process aligns with the expected behavior.

![Screenshot (2428)](https://github.com/user-attachments/assets/4870bf35-0b91-45a1-8454-f9fc2be23e01)
![Screenshot (2427)](https://github.com/user-attachments/assets/b477575c-6fc8-4058-a6b3-b5d16acdde90)

**Comment by brankoconjic** [comment]
Hi,

Please reach out to our support: hello@lemonsqueezy.com

Thanks!
