### ISSUE TITLE
Update payment method overlay doesn't use the theme configured in the dashboard

### ISSUE THREAD

**Issue by arfath-linklet** [lmsqueezy/lemonsqueezy.js#123]
This works fine for 'checkout' overlays. Doesn't work with 'update payment method' overlays

Dashboard configured overlay -
![image](https://github.com/user-attachments/assets/6638c29b-0154-4f73-b2ef-d7376f23976b)

In-app overlay -
![image](https://github.com/user-attachments/assets/e89638a6-e971-4d61-bc20-4d4b074b3b29)

**Comment by brankoconjic** [comment]
Hi,

This should be fixed with the recent Lemon Squeezy API changes. We now also support additional color options for overriding the Checkout via API.

**Comment by arfath-linklet** [comment]
I would reopen the same. This works fine for 'checkout' overlays either configured from dashboard or created via API with custom color options. But doesn't work with 'update payment method', default overlay doesn't match the configured from dashboard and there is no API to create an 'update payment method' with custom color options (that I am aware of).
