### ISSUE TITLE
Doesn't get proper user that exists in the LS customers list.

### ISSUE THREAD

**Issue by yuri-karkh** [lmsqueezy/lemonsqueezy.js#128]
"@lemonsqueezy/lemonsqueezy.js": "^3.3.0",

import {
  lemonSqueezySetup,
  listCustomers,
} from '@lemonsqueezy/lemonsqueezy.js'

const { error, data } = await listCustomers({
        filter: { email: user.email },
      })

Doesn't get proper user that exists in the LS customers list.

Data is always empty for the new customers, for very old customers this works fine. How this depends? Could u please help?

**Comment by brankoconjic** [comment]
Hi,

I could not reproduce this on my end, so I assume this has to be cache-related in your app.

Try using curl to fetch that. https://docs.lemonsqueezy.com/api/customers#list-all-customers

**Comment by yuri-karkh** [comment]
@brankoconjic I just checked via postman and it looks the same, I also double checked that user exists in the list of customers in LS. For my user it fetch correctly via filter as it is very very old user. Please see attached.
![screen3](https://github.com/user-attachments/assets/91e11af4-1213-4f7c-9a3e-464b6b0ffa1e)
![screen2](https://github.com/user-attachments/assets/29e602a3-3cd0-4f25-b9af-ecdde9d43ce8)
![screen1](https://github.com/user-attachments/assets/1323d3c9-af2f-4792-ad36-5eded9a8b4d2)

**Comment by yuri-karkh** [comment]
hey guys, any help? Still reproducable my side...

**Comment by yuri-karkh** [comment]
> I tested again using multiple accounts and couldn’t replicate the issue.
> 
> Ensure that you’re using the correct API key for the mode (Test or Live), as each mode requires a different key. If the problem persists, please reach out to `hello@lemonsqueezy.com` to open a support ticket.

@brankoconjic I regenerated the API key and it is solved, thanks for pointing!
