### ISSUE TITLE
A lot of invalid types

### ISSUE THREAD

**Issue by skoshx** [lmsqueezy/lemonsqueezy.js#19]
Just a while of using this package, and it feels like there are type inconsistencies between the TypeScript types and the docs in almost every function.

From this:
```typescript
const customer = await ls.getCustomer({
    id: customerEntry.id,
    include: ["subscriptions"],
  })
```

Returns invalid types. Says that `customer.included` is of type `Record<string, any> | undefined`, when in reality it's of type `Array<Record<string, any>> | undefined`.

The customers returned from `ls.getCustomers({ email })` has entries where `id` is of type `string`, when the API expects the user ID's to be of type `number`... Using the string works, but the types give errors, and to be honest, it's quite inconsistent that it's sometimes a number and sometimes a string.

**Comment by brankoconjic** [comment]
Fixed with v2.0.0.
