### ISSUE TITLE
Node: Error when running

### ISSUE THREAD

**Issue by jramosss** [lmsqueezy/lemonsqueezy.js#24]
Is this library able to be used with node?
When running with ts-node i'm getting:

Error [ERR_REQUIRE_ESM]: require() of ES Module ...../node_modules/@lemonsqueezy/lemonsqueezy.js/dist/index.js from ...../utils/lemonUtils.ts not supported.
Instead change the require of index.js in ..../utils/lemonUtils.ts to a dynamic import() which is available in all CommonJS modules.

I'm just importing as the docs says
`import LemonSqueezy from '@lemonsqueezy/lemonsqueezy.js'`

**Comment by gilbitron** [comment]
This is fixed in [v1.2.2](https://github.com/lmsqueezy/lemonsqueezy.js/releases/tag/v1.2.2)
