### ISSUE TITLE
[Feature Request] Types export

### ISSUE THREAD

**Issue by jramosss** [lmsqueezy/lemonsqueezy.js#25]
It would be great if we could use some types in our app like for example `SubscriptionObject`, if we want to store a user subscription in a class.

**Comment by Jaaneek** [comment]
I would also love it, I'm creating webhooks and would love to reuse already defined types. I already did that with lemonsqueezy.ts

If you need help with implementing this, let me know

**Comment by cherniavskii** [comment]
While the types are not exported from the package, I'm deriving them from the client methods.
Here are some examples:

```ts
const lemonClient = new LemonSqueezy(/** */);

type SubscriptionResponse = Awaited<ReturnType<typeof lemonClient.getSubscription>>;
type OrderResponse = Awaited<ReturnType<typeof lemonClient.getOrder>>;
type SubscriptionInvoicesResponse = Awaited<ReturnType<typeof lemonClient.getSubscriptionInvoice>>;
```

**Comment by brankoconjic** [comment]
Types are now exported with v2.0.0.

**Comment by Chinoman10** [comment]
Came here looking for exported types of incoming webhook requests...
But seems like they weren't included in this 'fix'.

I went ahead and opened a new issue: #140
