### ISSUE TITLE
Typescript types no longer generated in 1.2.4

### ISSUE THREAD

**Issue by Gbuomprisco** [lmsqueezy/lemonsqueezy.js#32]
Starting version 1.2.4, the Typescript types get no longer generated. 

Working okay in 1.2.2

To reproduce:
- Install 1.2.4
- Visit the dist folder: TS types are not generated

- Install 1.2.2
- Visit the dist folder: TS types are generated

**Comment by MariuszKogut** [comment]
Also came accross this issue. Types are no longer part of the package:

![image](https://github.com/lmsqueezy/lemonsqueezy.js/assets/9637281/cc1430f3-28fb-4d72-8c43-0649ecaad971)

**Comment by ymansurozer** [comment]
I was about to lose my mind when I came across this issue. Please fix this people.

**Comment by Quilljou** [comment]
Same here

**Comment by statusunknown418** [comment]
completely broke my app

**Comment by Gbuomprisco** [comment]
Workaround: Fix the package version to 1.2.2 in your package.json

**Comment by Gbuomprisco** [comment]
@mauryaratan pinging in case you haven't seen this yet - it's likely just a matter of rebuilding locally and publishing a new version.

**Comment by Nedi11** [comment]
this needs to be fixed
