### ISSUE TITLE
Error Prompting for Types Library Installation in Version 1.2.4

### ISSUE THREAD

**Issue by atpsito** [lmsqueezy/lemonsqueezy.js#36]
I've installed version 1.2.4, and it's prompting me to install a types library for which I don't have the necessary access to install. This seems to be causing an issue.

<img width="849" alt="Screenshot 2023-12-14 at 20 42 21" src="https://github.com/lmsqueezy/lemonsqueezy.js/assets/23362673/55f36e70-196b-4dd2-b9b7-af88113b6c81">

<img width="1134" alt="Screenshot 2023-12-14 at 20 41 47" src="https://github.com/lmsqueezy/lemonsqueezy.js/assets/23362673/ea769330-30fe-4aaf-a83e-10dbd3e085a4">

**Comment by Drakeoon** [comment]
It looks like something went wrong when the package was built & published. Previous published version (1.2.2) [has all required files in dist](https://www.npmjs.com/package/@lemonsqueezy/lemonsqueezy.js/v/1.2.2?activeTab=code), whereas [1.2.4 only ships index.cjs](https://www.npmjs.com/package/@lemonsqueezy/lemonsqueezy.js/v/1.2.4?activeTab=code)

Hope that helps!

**Comment by Nedi11** [comment]
When fix

**Comment by brankoconjic** [comment]
Thanks for reporting this. This issue has been reported in several other threads. Let's keep the track here: [#32](https://github.com/lmsqueezy/lemonsqueezy.js/issues/32)
