### ISSUE TITLE
Failed to resolve entry for package "@lemonsqueezy/lemonsqueezy.js

### ISSUE THREAD

**Issue by AF1QUE** [lmsqueezy/lemonsqueezy.js#38]
What am I doing wrong?

<img width="1130" alt="Screenshot 2023-12-19 at 11 18 44 PM" src="https://github.com/lmsqueezy/lemonsqueezy.js/assets/46385375/78712731-56f5-4212-b54c-dfaf2d652bc5">

<img width="1440" alt="Screenshot 2023-12-19 at 11 19 00 PM" src="https://github.com/lmsqueezy/lemonsqueezy.js/assets/46385375/17603e24-59d0-47f7-bcda-8e2e7990abab">

**Comment by Nedi11** [comment]
use version 1.2.2 they broke 1.2.4

**Comment by Nedi11** [comment]
Also do import {LemonSqueezy} from ""

**Comment by AF1QUE** [comment]
> use version 1.2.2 they broke 1.2.4

Yes, I did end up using version 1.2.2 and it worked. Thanks for leaving your comment though.

**Comment by brankoconjic** [comment]
Thanks for reporting this. This issue has been reported in several other threads. Let's keep the track here: [#32](https://github.com/lmsqueezy/lemonsqueezy.js/issues/32)
