### ISSUE TITLE
Rewrote the JavaScript SDK for all the APIs to fix some issues.

### ISSUE THREAD

**Issue by keyding** [lmsqueezy/lemonsqueezy.js#45]
I rewrote the JavaScript SDK for all APIs based on the official API documentation to fix unresolved issues and incorporate missing functions.

> This is the unofficial JavaScript/TypeScript SDK for Lemon Squeezy.
> Please read the [API introduction page](https://docs.lemonsqueezy.com/api) to understand how the API works.

https://github.com/heybrostudio/lemonsqueezy.js. 

[Functions Usage Wiki](https://github.com/heybrostudio/lemonsqueezy.js/wiki). 

**Features**
- **Type Strong**: Written in [TypeScript](https://www.typescriptlang.org/), with [TS Docs](https://github.com/microsoft/tsdoc)
- **Fully tree shakeable**: Only take what you want, [bundle size](https://github.com/heybrostudio/lemonsqueezy.js#bundle-size)
- **One-to-one implementation** with the official [API documentation](https://docs.lemonsqueezy.com/api)
- **Real-time synchronization** with official [API changelog](https://docs.lemonsqueezy.com/api/changelog)

**Fix issues**

- https://github.com/lmsqueezy/lemonsqueezy.js/issues/35 - Use the functions [`activateLicense`](https://github.com/heybrostudio/lemonsqueezy.js/wiki/License#activatelicense), [`validateLicense`](https://github.com/heybrostudio/lemonsqueezy.js/wiki/License#validatelicense).
- https://github.com/lmsqueezy/lemonsqueezy.js/issues/29 - Use the function [`updateCustomer`](https://github.com/heybrostudio/lemonsqueezy.js/wiki/Customers#updatecustomer).
- https://github.com/lmsqueezy/lemonsqueezy.js/issues/28 - See the use of [Customers](https://github.com/heybrostudio/lemonsqueezy.js/wiki/Customers) functions.
- https://github.com/lmsqueezy/lemonsqueezy.js/issues/25 - See the use of [Subscriptions](https://github.com/heybrostudio/lemonsqueezy.js/wiki/Subscriptions). See the [wiki](https://github.com/heybrostudio/lemonsqueezy.js/wiki) for more.
- https://github.com/lmsqueezy/lemonsqueezy.js/issues/22 -  Use the functions [`deactivatelicense`](https://github.com/heybrostudio/lemonsqueezy.js/wiki/License#deactivatelicense).
- https://github.com/lmsqueezy/lemonsqueezy.js/issues/19 - See the use of [Customers](https://github.com/heybrostudio/lemonsqueezy.js/wiki/Customers) functions. See the [wiki](https://github.com/heybrostudio/lemonsqueezy.js/wiki) for more.

Feel free to raise any issues for discussion and communication. ✨

**Comment by keyding** [comment]
> Thank you for the hard work! Can we just merge it into lemonsqueezy.js, not public types are very problematic if we want to write typesafe code 🙏

It's perfectly fine. Do I need to create a PR or do you do the merge yourself?

**Comment by brankoconjic** [comment]
@keyding, this is fantastic work! Could you please create a pull request for the merge? I'll take care of ensuring it's properly integrated.

Thanks!

**Comment by keyding** [comment]
> @keyding, this is fantastic work! Could you please create a pull request for the merge? I'll take care of ensuring it's properly integrated.
> 
> 
> 
> Thanks!

Okay.I'm going to set up a PR.🎉

**Comment by keyding** [comment]
> > @keyding, this is fantastic work! Could you please create a pull request for the merge? I'll take care of ensuring it's properly integrated.
> > Thanks!
> 
> Okay.I'm going to set up a PR.🎉

🎉 https://github.com/lmsqueezy/lemonsqueezy.js/pull/48
