### ISSUE TITLE
Checkout url redirects and wipes out custom data

### ISSUE THREAD

**Issue by btahir** [lmsqueezy/lemonsqueezy.js#46]
Hi - 

I think the custom data passing via url flow is broken. 

If you navigate to a url which is of the form

https://[STORE].lemonsqueezy.com/checkout/buy/[VARIANT_ID]?checkout[custom][user_id]=123

it automatically redirects to

https://[STORE].lemonsqueezy.com/checkout

and the custom data is not passed to the webhook.

https://docs.lemonsqueezy.com/help/checkout/passing-custom-data

I also tried creating checkout via the API but the url generated with the signature also redirected and I got no custom data.

For the API, the url generated looks something like `https://[STORE].lemonsqueezy.com/checkout/custom/389fb759-4a38-4ec3-80f8-928b36cf1e34?signature=5fabb4afd3dad1432ab20...` but this too redirects.

Code to create checkout with a custom field

```
let attributes = {
    checkout_data: {
      custom: {
        custom_field: 'custom_value',
      },
    },
  }

  try {
    const checkout = await ls.createCheckout({
      storeId: 123,
      variantId: 123,
      attributes,
    })

    return Response.json(
      { error: false, url: checkout['data']['attributes']['url'] },
      { status: 200 }
    )
  } catch (e: any) {
    return Response.json({ error: true, message: e.message }, { status: 400 })
  }
```

Appreciate any help on this!

**Comment by keyding** [comment]
✅ Using the latest version will solve your problem. 

Here is a simple example:

https://github.com/keyding/lemonsqueezy.js-issue-46.git

```ts
import { lemonSqueezySetup, createWebhook, listVariants, createCheckout } from '@lemonsqueezy/lemonsqueezy.js'

lemonSqueezySetup({ apiKey: import.meta.env.LEMON_SQUEEZY_API_KEY })

// Create a webhook
const STORE_ID = import.meta.env.LEMON_SQUEEZY_STORE_ID

const webhookRes = await createWebhook(STORE_ID, {
	url: "https://google.com/webhooks",
  events: ["order_created"],
  secret: "GOOGLE_WEBHOOKS_SECRET",
})
console.log("A webhooks is created: ", webhookRes.statusCode === 201)

// Get a variant id
const variantId = (await listVariants()).data!.data[0].id;

// Create a checkout
const { data, statusCode } = await createCheckout(STORE_ID, variantId, {
  checkoutData: {
    custom: {
      hello: 'lemonsqueezy.js'
    }
  }
})

console.log("A checkout is created: ", statusCode === 201)
console.log(data?.data.attributes.url)
```

Code execution results:

```bash
# bun run index.ts

A webhooks is created:  true
A checkout is created:  true
https://store.amazonus.app/checkout/custom/9edf8775-xxxx-4d42-xxxx-c725d934c304?signature=xxxxxxxxx
```

webhook created successfully.

![webhook](https://github.com/lmsqueezy/lemonsqueezy.js/assets/20431351/d4b905a0-450e-498c-9163-7ea9debd693b)

Submit your order via the generated checkout link.

![order_created](https://github.com/lmsqueezy/lemonsqueezy.js/assets/20431351/f99f7c62-070f-43cd-a430-6690d19961ce)

`order_created` is triggered with custom data in the `meta`.

Hopefully these will help!

**Comment by btahir** [comment]
This works now. Thank you!
