### ISSUE TITLE
getProduct parameter type

### ISSUE THREAD

**Issue by designersdecode** [lmsqueezy/lemonsqueezy.js#49]
Hi,
I found  a discrepancy in the `id` type.
Is `getProduct({ id })` `string` or `number`? [README doc](https://github.com/lmsqueezy/lemonsqueezy.js?tab=readme-ov-file#getproductparameters) says it's a number but [the source](https://github.com/lmsqueezy/lemonsqueezy.js/blob/c048b262fb7ff9604a321c7aaeaff6d27faa8b8c/src/types/methods.ts#L77) says it's a string.

**Comment by brankoconjic** [comment]
Hi,

This has been fixed with the v2.0.0. Please see: https://github.com/lmsqueezy/lemonsqueezy.js/wiki/Products#getproduct
