### ISSUE TITLE
Is this under development?

### ISSUE THREAD

**Issue by jatinhariani** [lmsqueezy/lemonsqueezy.js#5]
Getting a lot of issues using this with NestJS and typescript. Is this library still being built?

**Comment by jatinhariani** [comment]
Could explain with examples if that is not the case.

Also, are you guys accepting any volunteer help? I will see if I can help.

**Comment by wong2** [comment]
Same here, I doubt this is production ready.

**Comment by danrowden** [comment]
@jatinhariani Yes we are actively working on this package. Please feel free to share any issues you're facing or make pull requests with suggested changes 👍🏼
