### ISSUE TITLE
Is this a client side library?

### ISSUE THREAD

**Issue by coleridge72** [lmsqueezy/lemonsqueezy.js#55]
I noticed this in the readme:

> Do not use this package directly in the browser, as this will expose your API key. This would give anyone full API access to your Lemon Squeezy account and store(s). 

I may be in the wrong place - but how can I use [lemon.js](https://docs.lemonsqueezy.com/help/lemonjs/what-is-lemonjs) in particular, [handling events](https://docs.lemonsqueezy.com/help/lemonjs/handling-events) on the client side?

Thanks

**Comment by brankoconjic** [comment]
Hey @coleridge72,

"lemonsqueezy.js" is a Javascript SDK for the Lemon Squeezy API: https://docs.lemonsqueezy.com/api

The SDK is designed for backend use and does not offer methods for frontend interaction.

"lemon.js" is a simple JavaScript library for bringing some Lemon Squeezy functionalities, such as:

- [Open Lemon Squeezy Checkout & Payment Method Update overlays (iframes)](https://docs.lemonsqueezy.com/help/lemonjs/opening-overlays)
- [Listen to & handle checkout & payment details overlay events](https://docs.lemonsqueezy.com/help/lemonjs/handling-events)

For example, in React, you could do something like this:

```tsx
useEffect(() => {
    window.createLemonSqueezy();
    window.LemonSqueezy.Setup({
        eventHandler: (event) => {
        // Do whatever you want with this event data
            console.log(event);
	},
    });
});
```

assuming you already loaded lemon.js script in your app.

**Comment by coleridge72** [comment]
Thanks for clarifying!
