### ISSUE TITLE
Close button in overlay not working

### ISSUE THREAD

**Issue by mtkgeek** [lmsqueezy/lemonsqueezy.js#56]
Hi, i'm using the frontend script `<script src="https://app.lemonsqueezy.com/js/lemon.js" defer></script>` and just noticed the close icon at the top right corner of the checkout overlay doesn't work at any point during checkout

**Comment by mtkgeek** [comment]
The only errors i see in my console is  `Uncaught ReferenceError: LemonSqueezy is not defined` which is weird for two reasons

1. This should not cause the overlay issue
2.  I can confirm that the script is indeed downloaded when I look at the network tab but for some reason, this error shows up. This is from this chunk of code I have in my script tag

window.addEventListener("DOMContentLoaded", function () {

        ```
LemonSqueezy.Setup({
            eventHandler: (event) => {
                if (event.event == "Checkout.Success") {
                    console.log("checkout successs");
                    processPayment(event.data);
                }

            },
        });
    });
```

**Comment by mtkgeek** [comment]
Ok. So i downloaded the lemon.js script and added `window.LemonSqueezy = y();` to the end of the script and that fixed the `Uncaught ReferenceError: LemonSqueezy is not defined` error. Close button still doesn't work though.

**Comment by brankoconjic** [comment]
Try calling `window.createLemonSqueezy();` instead.

Could you create a minimal reproduction so that I can take a closer look into that?
