### ISSUE TITLE
An internal server error of 500 occurred updating a subscription item

### ISSUE THREAD

**Issue by keyding** [lmsqueezy/lemonsqueezy.js#57]
An internal server error of 500 occurred updating a subscription item.

API Reference: [Update a subscription item](https://docs.lemonsqueezy.com/api/subscription-items#update-a-subscription-item)

```bash
curl -X "PATCH" "https://api.lemonsqueezy.com/v1/subscription-items/211097" \
     -H 'Authorization: Bearer {api_key}' \
     -H 'Content-Type: application/vnd.api+json' \
     -H 'Accept: application/vnd.api+json' \
     -d $'{
  "data": {
    "type": "subscription-items",
    "id": "211097",
    "attributes": {
      "quantity": 10
    }
  }
}'
```

![500](https://github.com/lmsqueezy/lemonsqueezy.js/assets/20431351/18e6a7d7-c76c-40c8-984c-c76488087747)

**Comment by empresarrollo** [comment]
It keeps giving a 500 error :(

**Comment by brankoconjic** [comment]
Thank you for reporting this. It will be fixed in the next couple of days.
