### ISSUE TITLE
Types not released to package

### ISSUE THREAD

**Issue by wong2** [lmsqueezy/lemonsqueezy.js#6]

**Comment by danrowden** [comment]
It's coming soon!

**Comment by wong2** [comment]
I believe you should keep this issue open until the types are released.

**Comment by wong2** [comment]
https://github.com/lmsqueezy/lemonsqueezy.js/issues/4
I just discovered this issue, if it remains open, I would have opened this duplicate issue.

**Comment by wong2** [comment]
So please re-open either of these issues.
