### ISSUE TITLE
Add support for `invoice_immediately` in `subscription-items`

### ISSUE THREAD

**Issue by elie222** [lmsqueezy/lemonsqueezy.js#60]
This was recently added to the API but isn't available via this package yet:
https://docs.lemonsqueezy.com/api/subscription-items#update-a-subscription-item

**Comment by keyding** [comment]
HI, @elie222.

I'll submit a PR once the official API fixes this issue. https://github.com/lmsqueezy/lemonsqueezy.js/issues/57

**Comment by keyding** [comment]
The update function will have a break change, which I have to admit is a design error on my part. Sorry for the inconvenience!

Before:

```ts
updateSubscriptionItem(123, 10);
```

After:

```ts
updateSubscriptionItem(123, {
  quantity: 20,
  invoiceImmediately: true,
});
```

**Comment by brankoconjic** [comment]
> The updateSubscriptionItem function will have a break change, which I have to admit is a design error on my part. Sorry for the inconvenience!
> 
> Before:
> 
> ```ts
> updateSubscriptionItem(123, 10);
> ```
> 
> After:
> 
> ```ts
> updateSubscriptionItem(123, {
>   quantity: 20,
>   invoiceImmediately: true,
> });
> ```

We'll probably have to support both the old and the new signature (deprecate the old one), at least until the next major version is released.

**Comment by keyding** [comment]
> > The updateSubscriptionItem function will have a break change, which I have to admit is a design error on my part. Sorry for the inconvenience!
> 
> > 
> 
> > Before:
> 
> > 
> 
> > ```ts
> 
> > updateSubscriptionItem(123, 10);
> 
> > ```
> 
> > 
> 
> > After:
> 
> > 
> 
> > ```ts
> 
> > updateSubscriptionItem(123, {
> 
> >   quantity: 20,
> 
> >   invoiceImmediately: true,
> 
> > });
> 
> > ```
> 
> 
> 
> We'll probably have to support both the old and the new signature (deprecate the old one), at least until the next major version is released.
> 
> 

Yes, that's how it's being done currently.

**Comment by keyding** [comment]
PR. https://github.com/lmsqueezy/lemonsqueezy.js/pull/61
