### ISSUE TITLE
Mention alternative for deprecated method / property

### ISSUE THREAD

**Issue by EddyVinck** [lmsqueezy/lemonsqueezy.js#62]
I just started using the SDK, and have noticed some things I'm using seem to be deprecated. Finding out what to do instead can be a bit tricky as a first-time user.

![image](https://github.com/lmsqueezy/lemonsqueezy.js/assets/23434753/51fe347a-4e0c-45aa-ab08-da368b4934b1)

It would be a big improvement if these comments also mentioned what to use instead.

I do see this elsewhere in the file for the `VariantAttributes`, but this still leaves me to find out how to get the "Price objects" 

![image](https://github.com/lmsqueezy/lemonsqueezy.js/assets/23434753/8466c5b7-99ab-43da-bb6f-18437a44906a)

Side note: it doesn't help that some of the documentation still uses even older way of doing things. For example the use of `ls.someMethod()` here https://docs.lemonsqueezy.com/guides/tutorials/nextjs-saas-billing

Specifically I am not sure how to get the price of a variant properly right now. Some pointers here would be much appreciated.

If it helps at all, this is how I'm currently combining products and variants into plans for my application:

```ts
const products = await listProducts();
const variants = await listVariants({
  filter: {
    status: "published",
  },
});

if (!products.data || !variants.data) {
  throw new TRPCError({
    code: "INTERNAL_SERVER_ERROR",
    message: "Could not fetch products or variants",
  });
}

const productList = products.data.data.map((product) => {
  return {
    id: product.id,
    name: product.attributes.name,
    status: product.attributes.status,
    description: product.attributes.description,
  };
});
const variantsList = variants.data.data.map((variant) => {
  return {
    id: variant.id,
    name: variant.attributes.name, // Monthly, Yearly, etc
    interval: variant.attributes.interval, // "month", "year"
    intervalCount: variant.attributes.interval_count, // 1
    price: variant.attributes.price,
    status: variant.attributes.status,
    productId: `${variant.attributes.product_id}`,
    description: variant.attributes.description,
    slug: variant.attributes.slug,
  };
});

type Plan = {
  variantId: string;
  variantName: string;
  tagline: string;
  description: string;
  price: number;
  interval: string;
  intervalCount: number;
  link: string;
};

const plans: Plan[] = variantsList.map((variant) => {
  const product = productList.find(
    (product) => product.id === variant.productId,
  );
  return {
    variantId: variant.id,
    variantName: `${product?.name}`,
    tagline: product?.description || "",
    description: variant.description,
    price: variant.price,
    interval: variant.interval as string,
    intervalCount: variant.intervalCount as number,
    link: createCheckoutLink({ slug: variant.slug, user: user }),
  };
});
```

**Comment by brankoconjic** [comment]
Hey @EddyVinck,

Take a look into the [Price object docs](https://docs.lemonsqueezy.com/api/prices#the-price-object).

An important thing to note is that when a Variant's price is changed a new Price object is created. All old prices are retained. So, fetching prices will return an array of Prices, the first one returned being the current price of the variant.

Here's an example.

```tsx
// Fetch products from the Lemon Squeezy store, include variants.
const products = await listProducts({
    filter: { storeId: process.env.LEMONSQUEEZY_STORE_ID },
    include: ["variants"],
});

// Loop through all the variants.
const allVariants = products.data?.included as Variant["data"][] | undefined;

allVariants?.forEach(async (v) => {
    const variant = v.attributes;

    // Skip if draft.
    if ( variant.status === "draft")) {
      return;
    }

    // List prices.
    const variantPriceObject = await listPrices({
      filter: {
        variantId: v.id,
      },
    });

    // Get the first one
    console.log(
      variantPriceObject.data?.data.at(0)?.attributes,
    );
});
```

Also, another important thing to mention is that a product will always have at least one variant. If only one variant exists for a product, it is considered the “default” variant and is not shown as a separate option at checkout. It will also have a `pending` status. See the  [Variant object docs](https://docs.lemonsqueezy.com/api/variants#the-variant-object).

**Comment by EddyVinck** [comment]
Thanks for the example @brankoconjic
