### ISSUE TITLE
Feature Request: Add support for relative price-model endpoints

### ISSUE THREAD

**Issue by alexgrozav** [lmsqueezy/lemonsqueezy.js#63]
Would love to have support for the price model endpoint, which I've been using so far to get the real price value for Volume Pricing model.

```
"price-model": {
  "links": {
    "related": "https://api.lemonsqueezy.com/v1/variants/1/price-model",
    "self": "https://api.lemonsqueezy.com/v1/variants/1/relationships/price-model"
  }
}
```

**Comment by brankoconjic** [comment]
Thank you for the feature request - this has been added to our to-do list!
