### ISSUE TITLE
Add support for various env vars depending on runtime.

### ISSUE THREAD

**Issue by MrAlex94** [lmsqueezy/lemonsqueezy.js#66]
I have a Remix project that is being deployed on Cloudflare Pages. For the most part, when running a local deployment, I can use a `.dev.vars` file, which works when running `vite dev` and also using `wrangler` to preview a deployment.

Unfortunately, it appears that `lemonsqueezy.js` will only pick up env vars if they are defined in a `.env` file, meaning we need to have duplicate env var files during development.

Clerk, for example, handles this using a utility file that supports various runtime env vars: https://github.com/clerk/javascript/blob/9c34a756efa68d430e2231547576a20a6d9e6dc0/packages/remix/src/utils/utils.ts#L45

It would be great if lemonsqueezy adopted a similar method.

**Comment by brankoconjic** [comment]
Not sure what you mean, but the `lemonSqueezySetup` function expects an API key to be passed in as a parameter. It's up to you to decide how to retrieve it from the environment.

https://github.com/lmsqueezy/lemonsqueezy.js/blob/main/src/internal/setup/index.ts

**Comment by MrAlex94** [comment]
Ah sorry, you're absolutely correct. I've been working with a few libraries today and must've gotten things muddled up; my mistake! Indeed, we're passing along the key so can call it how we please. Sorry about that!
