### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by cleve02** [lmsqueezy/lemonsqueezy.js#7]
I'm getting this error trying to run lemon.js after installation

ERROR in ./node_modules/@lemonsqueezy/lemonsqueezy.js/index.js 4:8
Module parse failed: Unexpected token (4:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default class LemonSqueezy {
| 
>   apiKey;
|   apiUrl = 'https://api.lemonsqueezy.com/';
| 
 @ ./app/routes/Screens/Upgrade.js 25:0-57 60:21-33
 @ ./app/routes/index.js
 @ ./app/components/App/AppClient.js
 @ ./app/components/App/index.js
 @ ./app/index.js
 @ multi ./app/index.js

**Comment by danrowden** [comment]
It looks like you don't have support for `.js` files in your webpack config.

**Comment by remorses** [comment]
@danrowden You are using es modules without adding "type: module" in the package.json

**Comment by danrowden** [comment]
@cleve02 Can you try with v1.2.0?

**Comment by Schmedu** [comment]
> @cleve02 Can you try with v1.2.0?

I had the same issue before and it's working now 🙌🏼 Thanks @danrowden
