### ISSUE TITLE
Checkout links not working on firefox

### ISSUE THREAD

**Issue by aniito** [lmsqueezy/lemonsqueezy.js#77]
![image](https://github.com/lmsqueezy/lemonsqueezy.js/assets/66576504/d55c50bb-2702-4cff-92fc-dc2bd9b3e614)

**Comment by brankoconjic** [comment]
Hey,

Can you share more details on this?

**Comment by Adherentman** [comment]
i have same error,
use createCheckout api get checkoutUrl `https://{store}.lemonsqueezy.com/checkout/custom/{x}?signature={x}`
then i use `window.LemonSqueezy.Url.Open(checkoutUrl)` is work. 
but use `window.open(checkoutUrl, '_black')` get 404, redirected to `{store}.lemonsqueezy.com/checkout`

**Comment by Adherentman** [comment]
I found out that when I cleared the cookies, it worked fine.

**Comment by brankoconjic** [comment]
The fix for this is on the way.

**Comment by Yuniac** [comment]
Sorry to necro the issue. But just leaving this here in case it helps someone: Make sure your product is published and not Draft. Otherwise you will get a 404.
