### ISSUE TITLE
Expose the TS types to from the package

### ISSUE THREAD

**Issue by piotrkulpinski** [lmsqueezy/lemonsqueezy.js#80]
Hi, 
Is there any chance to expose the TypeScript types from the package? 
I'm using this package to implement custom dashboards for users and would like to be able to use the types returned by your API, like `OrderData` or `LicenseKeyData`.

Currently I have to do shenanigans like this to get the types:
```ts
type OrderData = NonNullable<Awaited<ReturnType<typeof listOrders>>["data"]>["data"][0]
```

Thanks!

**Comment by keyding** [comment]
Hi,
The type has been exported.

```ts
import { Order, ListOrders } from '@lemonsqueezy/lemonsqueezy.js'
```

[See source](https://github.com/lmsqueezy/lemonsqueezy.js/blob/8603bae687a45dbcef000c784949fa4356cdb96a/src/index.ts#L74)

I hope this helps.
