### ISSUE TITLE
Create checkout does not work

### ISSUE THREAD

**Issue by vaguue** [lmsqueezy/lemonsqueezy.js#87]
Hi. I'm trying to test this SDK, but I simply cannot make a checkout url with the code below:
```javascript
    //const { storeId, variantId, testMode } = ...;
    const newCheckout = {
      checkoutOptions: {
        embed: true,
        media: true,
        logo: true,
        dark: true,
      },
      checkoutData: {
        custom: {
          orderId: order.id,
        },
      },
      expiresAt: moment().add(...this.expireInterval).toISOString(),
      preview: true,
      testMode,
    };

    return createCheckout(storeId, variantId, newCheckout);
```

The problem is when I navigate to URL from the response I get an error "Invalid signature. Sorry, you are forbidden from accessing this page.". I tried all the different combinations of the parameters, and event empty object does not work.

**Comment by keyding** [comment]
Hi, @vaguue 

I tested it according to your parameters and it did not reproduce your problem, everything seems to be fine.

![crerateCheckout](https://github.com/lmsqueezy/lemonsqueezy.js/assets/20431351/e4bdfbf2-5afb-4da1-a709-e499ffb64d0a)

I hope this helps.

**Comment by vaguue** [comment]
Ok, sorry for bothering then, by now I'm actually confused what am I doing wrong... :)

**Comment by vaguue** [comment]
<img width="747" alt="Screenshot 2024-04-23 at 13 20 12" src="https://github.com/lmsqueezy/lemonsqueezy.js/assets/43249611/b430d5a4-1cf7-4d2f-9408-b35e97347353">
And now I get 500 0_o

**Comment by vaguue** [comment]
And the 500 error goes away once I add `email` to the parameters of the new checkout. 
```javascript
  async createOrderUrl({ order, user }) {
    const { storeId, variantId, testMode, redirectUrl } = this;
    const messages = getLang(orders, user);

    const newCheckout = {
      /*productOptions: {
        ...messages().product(order.finance.result),
      },*/
      checkoutOptions: {
        embed: true,
        media: true,
        logo: true,
      },
      checkoutData: {
        email: 'tita0x00@gmail.com',
        custom: {
          orderId: order.id,
        },
      },
      expiresAt: moment().add(...this.expireInterval).toISOString(),
      preview: true,
      testMode: this.testMode,
    };

    console.log(storeId, variantId, newCheckout);

    return createCheckout(storeId, variantId, newCheckout).then(resp => resp.data.data.attributes.url);
  }
```

**Comment by brankoconjic** [comment]
Hey @vaguue, can you confirm that this is now working as expected on your end? We made some changes on the platform to address these kinds of issues.
