### ISSUE TITLE
Support adding custom data when creating a new customer??

### ISSUE THREAD

**Issue by tonyabracadabra** [lmsqueezy/lemonsqueezy.js#89]
I am currently integrating your services into our authentication system and I've encountered a limitation that affects our operational efficiency. As it stands, we are using a workaround by overwriting the name field in customer data with a user ID to link Lemon Squeezy records with our authentication provider's user IDs. This approach is not ideal as it repurposes a field intended for other uses and complicates our data management.

Could you consider adding a feature to the createCustomer API that allows for including custom data fields? This addition would greatly enhance our ability to maintain clean and accurate data alignment between Lemon Squeezy and our authentication system, ultimately improving the service we provide to our users.

Thanks!

**Comment by brankoconjic** [comment]
Thank you for the suggestion, @tonyabracadabra. We don't have that planned for now, but you can leave a suggestion here: https://www.lemonsqueezy.com/suggest-feature and we will consider adding that in the future.
