### ISSUE TITLE
Are you changing the REST API without creating a new version?

### ISSUE THREAD

**Issue by TD-Developer** [lmsqueezy/lemonsqueezy.js#9]
In the docs for the checkouts endpoint [https://docs.lemonsqueezy.com/api/checkouts#create-a-checkout], checkout_data and custom are objects. The other day, I believe the api accepted checkout_data as an object, but now saying it should be an array with the following error:
`{
  "status": 422,
  "message": "Unprocessable Entity",
  "errors": [
    {
      "detail": "The checkout data must be an array.",
      "source": {
        "pointer": "/data/attributes/checkout_data"
      },
      "status": "422",
      "title": "Unprocessable Entity"
    }
  ]
}`

**Comment by danrowden** [comment]
We haven't made any changes to the API. If you're still seeing an issue please email support (hello@lemonsqueezy.com) with details and we'll look into it.
