### ISSUE TITLE
Add `generateOrderInvoice` and `generateSubscriptionInvoice` wiki

### ISSUE THREAD

**Issue by keyding** [lmsqueezy/lemonsqueezy.js#95]
([#93](https://github.com/lmsqueezy/lemonsqueezy.js/pull/93)) In the `Orders.md` file, add `generateOrderInvoice`. See [Orders.md](https://github.com/user-attachments/files/15542628/Orders.md).

([#94](https://github.com/lmsqueezy/lemonsqueezy.js/pull/94)) In the `SubscriptionInvoices.md` file, add `generateSubscriptionInvoice`. See [SubscriptionInvoices.md](https://github.com/user-attachments/files/15542655/SubscriptionInvoices.md).

**Comment by brankoconjic** [comment]
Thank you, Caven, for the awesome work as always!
